name: build

on:
  push: 
    branches:
      - main 

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: clean deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  build-pages:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        persist-credentials: false
    - name: Load Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: install
      run: npm install 
    - name: build 
      run: npm run build-only
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist